name: Build Android APK
run-name: ${{ github.event.inputs.repository }}:${{ github.event.inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/nightscout/AndroidAPS"
      jdkVersion:
        description: "OpenJDK version to use: 21"
        required: false
        default: "21"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Release"
        required: false
        default: "assembleFullRelease"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: |
          git clone --recurse-submodules --depth=1 ${{ github.event.inputs.repository }} workspace
          cd workspace
          git checkout ${{ env.td_commit_hash }}
          git show --summary

      - name: List Gradle Tasks
        working-directory: ./workspace
        run: ./gradlew tasks --all

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNINGKEYBASE64 }}" | base64 --decode > /tmp/keystore.jks
          ls -l /tmp/keystore.jks
          chmod 600 /tmp/keystore.jks

      - name: Validate Keystore
        run: |
          keytool -list -v -keystore /tmp/keystore.jks -storepass "${{ secrets.KEYSTOREPASSWORD }}"

      - name: Build APKs
        working-directory: ./workspace
        run: |
          ./gradlew assembleAndroidWearMicroRelease
          ./gradlew assembleFullRelease
          ./gradlew assembleWearFullRelease

      - name: Verify APK Files
        working-directory: ./workspace
        run: |
          ls ./workspace/app/build/outputs/apk || echo "No APKs found."
          ls ./workspace/app/build/outputs/apk/androidWearMicro || echo "No Wear Micro APK found."
          ls ./workspace/app/build/outputs/apk/fullRelease || echo "No Full Release APK found."

      - name: Upload the APK artifacts with 1-day retention
        uses: actions/upload-artifact@v4
        with:
          path: ./workspace/app/build/outputs/apk/**/*.apk
          name: apk-archive
          retention-days: 1

      - name: Debug Environment Variables
        run: |
          echo "td_version=${{ env.td_version }}"
          echo "td_commit_hash=${{ env.td_commit_hash }}"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: Android-${{ env.td_version || 'unknown' }}-${{ env.td_commit_hash || '0000000' }}
          name: Android ${{ env.td_version || 'unknown' }}-${{ env.td_commit_hash || '0000000' }}
          body: "View source code at: https://github.com/nightscout/AndroidAPS/tree/${{ env.td_commit_hash || '0000000' }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./workspace/app/build/outputs/apk/**/*.apk
