name: Build Android APK
run-name: ${{ github.event.inputs.repository }}:${{ github.event.inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/nightscout/AndroidAPS"
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "21"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Release"
        required: false
        default: "assembleFullRelease"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/androidaps-version.json'
          prefix: td

      # Set up JDK  (since Android Studio "Ladybug" requires it)
      - name: Setup JDK ${{ github.event.inputs.jdkVersion }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      # Clone project repository
      - name: Clone project
        run: |
          git clone --recurse-submodules ${{ github.event.inputs.repository }} workspace
          cd workspace
          git checkout ${{ env.td_commit_hash }}
          git show --summary
      
      # Make gradlew executable
      - name: Make gradlew executable
        working-directory: ./workspace
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew -q projects
      # List Directory Structure and Projects
      - name: List Directory Structure and Projects
        run: |
          echo "Directory structure:"
          ls -R ./workspace
          echo "Gradle projects:"
          ./gradlew projects
        working-directory: ./workspace
      
