name: Build Android APK
run-name: ${{ github.event.inputs.repository }}:${{ github.event.inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/nightscout/AndroidAPS"
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "17"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Release"
        required: false
        default: "assembleFullRelease"

jobs:
  build:
    runs-on: ubuntu-latest # Android SDK is built-in in this image
    steps:
      - uses: actions/checkout@v2

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/androidaps-version.json'
          prefix: td
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNINGKEYBASE64 }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: |
          git clone --recurse-submodules --depth=1 ${{ github.event.inputs.repository }} workspace
          cd workspace
          git checkout ${{ env.td_commit_hash }}
          git show --summary
      - name: Make gradlew executable
        working-directory: ./workspace
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew -q projects
          
      - name: Build APK
        run: ./gradlew assembleFullRelease app:app --stacktrace    
        working-directory: ./workspace
        env:
            SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
            SIGNING_KEY_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
            SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
      - name: Exe files
        run: |
          ls
      - uses: upup-company/apksigner-android@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: ./**/
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYSTOREPASSWORD }}
          customArgs: --v1-signing-enabled,true,--v2-signing-enabled,true
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload the APK artifact with 1 day retention
        uses: actions/upload-artifact@v4
        with:
          path: ./**/*.apk
          name: apk-archive
          retention-days: 1
          
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            tag: Android-${{ env.td_version }}-1${{ env.td_commit_hash }}
            name: Android ${{ env.td_version }}-1${{ env.td_commit_hash }}
            body: https://github.com/nightscout/AndroidAPS/tree/${{ env.td_commit_hash }}
            token: ${{ secrets.GITHUB_TOKEN }}
            artifacts: ./**/*.apk
