name: Build Android APK
run-name: ${{ github.event.inputs.repository }}:${{ github.event.inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/nightscout/AndroidAPS"
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "17"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Release"
        required: false
        default: "assembleFullRelease"

jobs:
  build:
    runs-on: ubuntu-latest # Android SDK is built-in in this image
    steps:
      - uses: actions/checkout@v2

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/androidaps-version.json'
          prefix: td
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: '.github/workflows/clientkeystore.jks'
          encodedString: ${{ secrets.SIGNINGKEYBASE64 }}
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: |
          git clone --recurse-submodules --depth=1 ${{ github.event.inputs.repository }} workspace
          cd workspace
          git checkout ${{ env.td_commit_hash }}
          git show --summary
      - name: Build APK
        working-directory: ./workspace
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          
          ./gradlew assembleFullRelease app
      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ./**/
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYSTOREPASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload the APK artifact with 1 day retention
        uses: actions/upload-artifact@v4
        with:
          path: ./**/*.apk
          name: apk-archive
          retention-days: 1
          
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            tag: Android-${{ env.td_version }}-1${{ env.td_commit_hash }}
            name: Android ${{ env.td_version }}-1${{ env.td_commit_hash }}
            body: https://github.com/nightscout/AndroidAPS/tree/${{ env.td_commit_hash }}
            token: ${{ secrets.GITHUB_TOKEN }}
            artifacts: ./**/*.apk
