name: Build Android APK
run-name: ${{ github.event.inputs.repository }}:${{ github.event.inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/nightscout/AndroidAPS"
      jdkVersion:
        description: "OpenJDK version to use: 21"
        required: false
        default: "21"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Release"
        required: false
        default: "assembleFullRelease"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/androidaps-version.json'
          prefix: td

      # Set up JDK 21 (since Android Studio "Ladybug" requires it)
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      # Clone project repository
      - name: Clone project
        run: |
          git clone --recurse-submodules ${{ github.event.inputs.repository }} workspace
          cd workspace
          git checkout ${{ env.td_commit_hash }}
          git show --summary

      # Make gradlew executable
      - name: Make gradlew executable
        working-directory: ./workspace
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew -q projects

      # Decode Keystore
      - name: Decode Keystore
        run: echo "${{ secrets.SIGNINGKEYBASE64 }}" | base64 --decode > /tmp/keystore.jks
        working-directory: ./workspace

      # Build APK (signed)
      - name: Build APK
        working-directory: ./workspace
        run: ./gradlew ${{ github.event.inputs.taskName }}  -Pandroid.injected.signing.store.file=/tmp/keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTOREPASSWORD }}  -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }}  -Pandroid.injected.signing.key.password=${{ secrets.KEYSTOREPASSWORD }}
      
      # Verify APK Files
      - name: Exe files
        run: |
          ls ./workspace/app/build/outputs/apk || echo "No APKs found."

      # Upload APK artifacts
      - name: Upload the APK artifact with 1 day retention
        uses: actions/upload-artifact@v4
        with:
          path: ./workspace/app/build/outputs/apk/**/*.apk
          name: apk-archive
          retention-days: 1

      # Create GitHub Release
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: Android-${{ env.td_version }}-${{ env.td_commit_hash }}
          name: Android ${{ env.td_version }}-${{ env.td_commit_hash }}
          body: "View source code at: https://github.com/nightscout/AndroidAPS/tree/${{ env.td_commit_hash }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./workspace/app/build/outputs/apk/**/*.apk
